"Untrusted data passed to external API","Data provided remotely is used in this external API without sanitization, which could be a security risk.","error","Call to flask.make_response [position 0] with untrusted data from [[""ControlFlowNode for ImportMember""|""relative:///2/vul.py:1:26:1:32""]].","/2/vul.py","7","26","7","52"
"Untrusted data passed to external API","Data provided remotely is used in this external API without sanitization, which could be a security risk.","error","Call to re.match [position 1] with untrusted data from [[""ControlFlowNode for ImportMember""|""relative:///1/vul.py:1:36:1:42""]].","/1/vul.py","9","45","9","50"
"Untrusted data passed to external API","Data provided remotely is used in this external API without sanitization, which could be a security risk.","error","Call to flask.redirect [position 0] with untrusted data from [[""ControlFlowNode for ImportMember""|""relative:///1/vul.py:1:36:1:42""]].","/1/vul.py","10","25","10","30"
